twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        site_name: '%env(resolve:SITE_NAME)%'
    paths:
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
