name: bigfoot-symfony
recipe: platformsh
config:

  # This section overrides Platform.sh configuration with values that make more
  # sense for local development.
  #
  # Note that "app" is the name of the application defined in your
  # .platform.app.yaml or applications.yaml.
  overrides:
    app:
      variables:
        env:
          APP_ENV: dev
          APP_DEBUG: 1
          BLACKFIRE_AGENT_SOCKET: "tcp://blackfire:8307"

services:
  blackfire:
    type: blackfire
    app_service: app
    server_id: <BLACKFIRE_SERVER_ID>
    server_token: <BLACKFIRE_SERVER_TOKEN>
    client_id: <BLACKFIRE_CLIENT_ID>
    client_token: <BLACKFIRE_CLIENT_TOKEN>

tooling:
  blackfire:
    cmd: /usr/local/bin/blackfire
    service: app

  blackfire-player:
    cmd: /usr/local/bin/blackfire-player
    service: app
